# Generated by Django 2.0.2 on 2018-02-19 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameGuess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p', models.FloatField()),
            ],
            options={
                'managed': False,
                'db_table': 'game_guess',
            },
        ),
        migrations.CreateModel(
            name='GameQuestionOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('th', models.FloatField()),
            ],
            options={
                'managed': False,
                'db_table': 'game_question_offer',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.NullBooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='AnswerGuess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.NullBooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('uid', models.UUIDField(primary_key=True, serialize=False)),
                ('play_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Guess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='right_guess',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Guess'),
        ),
        migrations.AddField(
            model_name='answerguess',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Game'),
        ),
        migrations.AddField(
            model_name='answerguess',
            name='guess',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Guess'),
        ),
        migrations.AddField(
            model_name='answer',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Game'),
        ),
        migrations.AddField(
            model_name='answer',
            name='guess',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Guess'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Question'),
        ),
    ]
